T1 ipvs
khannz/crispy-palm-tree pull request #81
Opened 2020-11-17 14:52 UTC by thevan4

release #58

2020-11-23 17:11 UTC, khannz requested changes
All good, кроме замечаний

2020-11-23 17:11 UTC, khannz commented on Makefile
> +	protoc -I ./proto/ --go_out=./t1-ipvs/grpc-orch/ --go-grpc_out=./t1-ipvs/grpc-orch/ ./proto/t1-orch.proto
Та же история. В чём ценность перезапускать генерацию `protobuf` атомарно?

2020-11-23 17:11 UTC, khannz commented on Makefile
> +	rm -f ./t1-dummy/lbost1ad
хм, а это здесь почему? Есть скрипт который в корень кода микросервиса кладёт бинарь?

2020-11-23 17:17 UTC, thevan4 commented on Makefile
> +	protoc -I ./proto/ --go_out=./t1-ipvs/grpc-orch/ --go-grpc_out=./t1-ipvs/grpc-orch/ ./proto/t1-orch.proto
Намного быстрее генерируется, чем на весь проект делать каждый раз даже без изменений. Не у всех i9)

2020-11-23 17:17 UTC, thevan4 commented on Makefile
> +	rm -f ./t1-dummy/lbost1ad
Есть, dummy-bin например и все схожие.

2020-11-23 17:25 UTC, thevan4 commented on Makefile
> +	cd t1-ipvs && go mod download
Модули могут обновляться и/или собираться независимо. Логику "пересобрать всё" можно сделать, но нужно иметь возможность вносить точечные изменения.

В скачивание отделено от билда для удобства отлова возможных ошибок, чтобы было видно этот этап (а так сборка автоматически начнёт скачивание модулей, если их ещё нет).

2021-01-13 10:40 UTC, khannz approved these changes

2021-01-13 10:43 UTC, merged